### ISSUE TITLE
'hit' method of Position class is missing return-type annotation

### ISSUE THREAD

**Issue by DanStevens** [glayzzle/php-reflection#26]
The [`hit` method of the `Position` class](https://github.com/glayzzle/php-reflection/blob/9e0977898069c30d7404a18fb14cb7b82021bcfb/index.d.ts#L87) is missing a return-type annotation, which results in the following error when compiling with Typescript:

    node_modules/php-reflection/index.d.ts:87:9 - error TS7010: 'hit', which lacks return-type annotation, implicitly has an 'any' return type.

Looking at the [implementation of the `hit` method](https://github.com/glayzzle/php-reflection/blob/9e0977898069c30d7404a18fb14cb7b82021bcfb/src/utils/position.js#L67), the return type should be `boolean`.

**Comment by DanStevens** [comment]
Patch: [0001-Fix-for-issue-26-https-github.com-glayzzle-php-refle.patch.txt](https://github.com/glayzzle/php-reflection/files/3472549/0001-Fix-for-issue-26-https-github.com-glayzzle-php-refle.patch.txt)

**Comment by ichiriac** [comment]
should be fixed in version 2.3.1
